const procs = [
  {
    id: "0",
    nombre: "proceso 0",
    descripcion: "descripcion proceso 0",
    fecha: "14/05/2022",
    estado: "Aceptado",
    pregunta: "cual es el mejor framework?",
    opciones: [
      { option: "ReactJS", votes: 0 },
      { option: "Angular", votes: 0 },
      { option: "EmberJS", votes: 0 },
      { option: "Vue", votes: 0 },
    ],
  },
  {
    id: "1",
    nombre: "proceso 1",
    descripcion: "descripcion proceso 1",
    fecha: "13/05/2022",
    estado: "Aceptado",
    pregunta: "cual es el mejor framework?",
    opciones: [
      { option: "ReactJS", votes: 0 },
      { option: "Angular", votes: 0 },
      { option: "EmberJS", votes: 0 },
      { option: "Vue", votes: 0 },
    ],
  },
  {
    id: "2",
    nombre: "proceso 2",
    descripcion: "descripcion proceso 2",
    fecha: "13/05/2022",
    estado: "Aceptado",
    pregunta: "cual es el mejor framework?",
    opciones: [
      { option: "ReactJS", votes: 0 },
      { option: "Angular", votes: 0 },
      { option: "EmberJS", votes: 0 },
      { option: "Vue", votes: 0 },
    ],
  },
  {
    id: "3",
    nombre: "proceso 3",
    descripcion: "descripcion proceso 3",
    fecha: "13/05/2022",
    estado: "Aceptado",
    pregunta: "cual es el mejor framework?",
    opciones: [
      { option: "ReactJS", votes: 0 },
      { option: "Angular", votes: 0 },
      { option: "EmberJS", votes: 0 },
      { option: "Vue", votes: 0 },
    ],
  },
  {
    id: "4",
    nombre: "proceso 4",
    descripcion: "descripcion proceso 4",
    fecha: "13/05/2022",
    estado: "Aceptado",
    pregunta: "cual es el mejor framework?",
    opciones: [
      { option: "ReactJS", votes: 0 },
      { option: "Angular", votes: 0 },
      { option: "EmberJS", votes: 0 },
      { option: "Vue", votes: 0 },
    ],
  },
  {
    id: "5",
    nombre: "proceso 5",
    descripcion: "descripcion proceso 5",
    fecha: "13/05/2022",
    estado: "Aceptado",
    pregunta: "cual es el mejor framework?",
    opciones: [
      { option: "ReactJS", votes: 0 },
      { option: "Angular", votes: 0 },
      { option: "EmberJS", votes: 0 },
      { option: "Vue", votes: 0 },
    ],
  },
  {
    id: "6",
    nombre: "proceso 6",
    descripcion: "descripcion proceso 6",
    fecha: "13/05/2022",
    estado: "Aceptado",
    pregunta: "cual es el mejor framework?",
    opciones: [
      { option: "ReactJS", votes: 0 },
      { option: "Angular", votes: 0 },
      { option: "EmberJS", votes: 0 },
      { option: "Vue", votes: 0 },
    ],
  },
];

export default procs;
